[colors]
background = "#1e2021FF"
text_primary = "#e3e2e3FF"
text_muted = "#c1c7ccFF"
accent_primary = "#a9ccdeFF"
accent_secondary = "#bbc8d1FF"
warning = "#d8bee0FF"
error = "#ffb4abFF"
insert_hint = "#d8bee080"
backdrop = "#42484bFF"

[colors.border]
focused = "#a9ccdeFF"
unfocused = "#42484bFF"
outer = "#121415FF"

[colors.overview]
background_tint = "#12141588"
badge = "#a9ccdeFF"
workspace_background = "#121415FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#d8bee0FF"
border_color_unfocused = "#422f4aFF"
