[colors]
background = "#1b211dFF"
text_primary = "#dee4ddFF"
text_muted = "#bdcabfFF"
accent_primary = "#70dba1FF"
accent_secondary = "#a6d0b5FF"
warning = "#bdc2ffFF"
error = "#ffb4abFF"
insert_hint = "#bdc2ff80"
backdrop = "#3e4941FF"

[colors.border]
focused = "#70dba1FF"
unfocused = "#3e4941FF"
outer = "#0f1511FF"

[colors.overview]
background_tint = "#0f151188"
badge = "#70dba1FF"
workspace_background = "#0f1511FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#bdc2ffFF"
border_color_unfocused = "#7f89e3FF"

[brightness]
enable_ddcutil = true

[brightness.monitor.DP-1]
backend = "dccutil"
